#! /usr/bin/env bash

__user_pip_completion()
{
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 ) )
}
complete -o default -F __pip_completion pip

__user_cdconfiguration_completion()
{
    COMPREPLY=( $(compgen -W "$(\ls ~/work/claw/configurations)" -- \
                "${COMP_WORDS[$COMP_CWORD]}" ) )
}
complete -F __user_cdconfiguration_completion cdconfiguration

__user_python_argcomplete() {
    local IFS=''
    COMPREPLY=( $(IFS="$IFS" \
                  COMP_LINE="$COMP_LINE" \
                  COMP_POINT="$COMP_POINT" \
                  _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS" \
                  _ARGCOMPLETE=1 \
                  "$1" 8>&1 9>&2 1>/dev/null 2>/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    fi
}
__user_python_completions=(
    clue
    claw
    je
    tmuxp
    docl
)
for __user_python_completion in ${__user_python_completions[@]}; do
    complete -o nospace -o default -F __user_python_argcomplete ${__user_python_completion}
done

_cfy_completion() {
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                       COMP_CWORD=$COMP_CWORD \
                       _CFY_COMPLETE=complete $1 ) )
}

complete -F _cfy_completion -o default cfy;
